### ISSUE TITLE
Kernel is not executing on DGX-1 environment

### ISSUE THREAD

**Issue by rahadi23** [rahadi23/parcomp-gpus#2]
Kernel is not executed even if it's written correctly.

For example when running `incrementMatrix`, we know that the input would be a sequence of number (produced by for loops):

`0 1 2 3 4 5 ...`

the expected result after increment should be:

Host result: `1 2 3 4 5 6 ...`
Device result: `1 2 3 4 5 6 ...`

However, the real result after the program terminates is as follow:

Host result: `1 2 3 4 5 6 ...`
Device result: `0 0 0 0 0 ...`

This is an indication that the kernel is not run correctly.

**Comment by rahadi23** [comment]
To pinpoint the cause of this issue, we first need to setup some debugging mechanism.

This can be done by adding a function to check for previous kernel execution error and log it if any:

```c
#define CUDACHECK(err)                    \
  do                                      \
  {                                       \
    cudaCheck((err), __FILE__, __LINE__); \
  } while (false)

inline void cudaCheck(cudaError_t error_code, const char *file, int line)
{
  if (error_code != cudaSuccess)
  {
    fprintf(stderr, "CUDA Error %d: '%s'. In file '%s' on line %d\n", error_code, cudaGetErrorString(error_code), file, line);
    fflush(stderr);
    exit(error_code);
  }
}
```

and later in the main code, we call it after kernel execution:

```c
int main()
{
	// ... some preparation codes ...

	// execute a kernel
	incrementArrayOnDevice<<<dimSize, blockSize>>>(...);

	// check for previous kernel execution error
	CUDACHECK(cudaPeekAtLastError());

	// ... some more codes ...

	return 0;
}
```

**Comment by rahadi23** [comment]
After applying the above debugging method, we found this error:

`CUDA error: the provided PTX was compiled with an unsupported toolchain`

upon further checking, this happen because of CUDA version mismatch between the device and the SDK. Therefore, the fix is to adjust the kubernetes pod's image to match the CUDA version of the environment, in this case DGX-1 to `CUDA 12.4` (based on `nvidia-smi` output).

By changing the image from `image: "nvcr.io/nvidia/nvhpc:24.9-devel-cuda_multi-ubuntu22.04"` to `image: "nvcr.io/nvidia/nvhpc:24.5-devel-cuda12.4-ubuntu22.04"`, the issue is no longer happening and the outputs are produced correctly as expected. See d9489768b06ac201ce984a6af5f3cfd847e0a39a for further details.

**Comment by srifqi** [comment]
Downgrading the image version does fix the issues for me, too. Thank you!

**Comment by rahadi23** [comment]
Hi @srifqi !
Thank you for the comments. Glad to hear that you found this issue helpful for your setup as well.
Good luck finishing the assignments to us all! 😄 💪
